
  const arr =
     [
        {
            "AdmNo": "9531",
            "Student_name": "SMRUTIRANJAN PRUSTY",
            "RollNo": "34",
            "Sec": "D",
            "ENGLISH": "35",
            "MATHEMATICS": "18",
            "SCIENCE": "17",
            "SST": "41",
            "LANG": "54"
        },
        {
            "AdmNo": "9657",
            "Student_name": "ANANYA DAS",
            "RollNo": "6",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "61",
            "SCIENCE": "62",
            "SST": "60",
            "LANG": "76"
        },
        {
            "AdmNo": "9659",
            "Student_name": "ADITI PATNAIK",
            "RollNo": "2",
            "Sec": "D",
            "ENGLISH": "64",
            "MATHEMATICS": "32",
            "SCIENCE": "30",
            "SST": "62",
            "LANG": "75"
        },
        {
            "AdmNo": "9660",
            "Student_name": "ADITEE TRIPATHY",
            "RollNo": "3",
            "Sec": "C",
            "ENGLISH": "73",
            "MATHEMATICS": "77",
            "SCIENCE": "68",
            "SST": "71",
            "LANG": "79"
        },
        {
            "AdmNo": "9661",
            "Student_name": "AYANA ROUTRAY",
            "RollNo": "9",
            "Sec": "A",
            "ENGLISH": "72",
            "MATHEMATICS": "32",
            "SCIENCE": "38",
            "SST": "71",
            "LANG": "74"
        },
        {
            "AdmNo": "9662",
            "Student_name": "ANWESHA ROUT",
            "RollNo": "9",
            "Sec": "F",
            "ENGLISH": "76",
            "MATHEMATICS": "75",
            "SCIENCE": "68",
            "SST": "78",
            "LANG": "79"
        },
        {
            "AdmNo": "9663",
            "Student_name": "ABHIPSHA PRIYADARSANI",
            "RollNo": "1",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "42",
            "SCIENCE": "54",
            "SST": "66",
            "LANG": "71"
        },
        {
            "AdmNo": "9664",
            "Student_name": "ANSHUMAN PANDA",
            "RollNo": "7",
            "Sec": "D",
            "ENGLISH": "63",
            "MATHEMATICS": "69",
            "SCIENCE": "49",
            "SST": "61",
            "LANG": "70"
        },
        {
            "AdmNo": "9665",
            "Student_name": "ADITYA SARANGI",
            "RollNo": "4",
            "Sec": "F",
            "ENGLISH": "78",
            "MATHEMATICS": "80",
            "SCIENCE": "72",
            "SST": "75",
            "LANG": "79"
        },
        {
            "AdmNo": "9666",
            "Student_name": "ADITI RATH",
            "RollNo": "4",
            "Sec": "C",
            "ENGLISH": "72",
            "MATHEMATICS": "49",
            "SCIENCE": "AB",
            "SST": "61",
            "LANG": "56"
        },
        {
            "AdmNo": "9667",
            "Student_name": "ANANYA KUMAR DAS",
            "RollNo": "9",
            "Sec": "C",
            "ENGLISH": "75",
            "MATHEMATICS": "68",
            "SCIENCE": "79",
            "SST": "76",
            "LANG": "74"
        },
        {
            "AdmNo": "9668",
            "Student_name": "AMISHA YASHASWANI",
            "RollNo": "5",
            "Sec": "D",
            "ENGLISH": "49",
            "MATHEMATICS": "13",
            "SCIENCE": "21",
            "SST": "39",
            "LANG": "68"
        },
        {
            "AdmNo": "9669",
            "Student_name": "ABHIJEET SABAR",
            "RollNo": "1",
            "Sec": "A",
            "ENGLISH": "63",
            "MATHEMATICS": "67",
            "SCIENCE": "51",
            "SST": "55",
            "LANG": "74"
        },
        {
            "AdmNo": "9671",
            "Student_name": "ADYASHIS AMLAN DAS",
            "RollNo": "2",
            "Sec": "A",
            "ENGLISH": "68",
            "MATHEMATICS": "72",
            "SCIENCE": "59",
            "SST": "59",
            "LANG": "69"
        },
        {
            "AdmNo": "9672",
            "Student_name": "ADITYA PATNAIK",
            "RollNo": "6",
            "Sec": "C",
            "ENGLISH": "65",
            "MATHEMATICS": "46",
            "SCIENCE": "57",
            "SST": "52",
            "LANG": "71"
        },
        {
            "AdmNo": "9673",
            "Student_name": "ANSUMAN SATAPATHY",
            "RollNo": "8",
            "Sec": "D",
            "ENGLISH": "67",
            "MATHEMATICS": "56",
            "SCIENCE": "43",
            "SST": "62",
            "LANG": "76"
        },
        {
            "AdmNo": "9674",
            "Student_name": "ALOUKIK DAS",
            "RollNo": "4",
            "Sec": "A",
            "ENGLISH": "70",
            "MATHEMATICS": "73",
            "SCIENCE": "73",
            "SST": "71",
            "LANG": "68"
        },
        {
            "AdmNo": "9675",
            "Student_name": "AKSHIT KUMAR SAHOO",
            "RollNo": "7",
            "Sec": "C",
            "ENGLISH": "75",
            "MATHEMATICS": "78",
            "SCIENCE": "71",
            "SST": "71",
            "LANG": "73"
        },
        {
            "AdmNo": "9676",
            "Student_name": "ANSHUMAN MISHRA",
            "RollNo": "6",
            "Sec": "D",
            "ENGLISH": "50",
            "MATHEMATICS": "38",
            "SCIENCE": "45",
            "SST": "57",
            "LANG": "64"
        },
        {
            "AdmNo": "9677",
            "Student_name": "ADYASHA ROUT",
            "RollNo": "2",
            "Sec": "B",
            "ENGLISH": "71",
            "MATHEMATICS": "59",
            "SCIENCE": "54",
            "SST": "66",
            "LANG": "73"
        },
        {
            "AdmNo": "9678",
            "Student_name": "ADYASHA MISHRA",
            "RollNo": "5",
            "Sec": "F",
            "ENGLISH": "73",
            "MATHEMATICS": "62",
            "SCIENCE": "57",
            "SST": "67",
            "LANG": "76"
        },
        {
            "AdmNo": "9679",
            "Student_name": "AMRITA PRIYADARSHINI",
            "RollNo": "8",
            "Sec": "C",
            "ENGLISH": "67",
            "MATHEMATICS": "67",
            "SCIENCE": "63",
            "SST": "70",
            "LANG": "69"
        },
        {
            "AdmNo": "9680",
            "Student_name": "ABHINASH SAHU",
            "RollNo": "1",
            "Sec": "D",
            "ENGLISH": "74",
            "MATHEMATICS": "79",
            "SCIENCE": "74",
            "SST": "77",
            "LANG": "78"
        },
        {
            "AdmNo": "9681",
            "Student_name": "ANWESH MOHANTY",
            "RollNo": "8",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "77",
            "SCIENCE": "61",
            "SST": "57",
            "LANG": "78"
        },
        {
            "AdmNo": "9682",
            "Student_name": "AISWARYANI NAYAK",
            "RollNo": "4",
            "Sec": "D",
            "ENGLISH": "55",
            "MATHEMATICS": "38",
            "SCIENCE": "26",
            "SST": "49",
            "LANG": "48"
        },
        {
            "AdmNo": "9684",
            "Student_name": "ABHILASH DASH",
            "RollNo": "1",
            "Sec": "C",
            "ENGLISH": "73",
            "MATHEMATICS": "74",
            "SCIENCE": "73",
            "SST": "73",
            "LANG": "77"
        },
        {
            "AdmNo": "9686",
            "Student_name": "AYUSHMAN SAHOO",
            "RollNo": "13",
            "Sec": "D",
            "ENGLISH": "63",
            "MATHEMATICS": "38",
            "SCIENCE": "47",
            "SST": "56",
            "LANG": "65"
        },
        {
            "AdmNo": "9687",
            "Student_name": "BISHWASWARUP NAYAK",
            "RollNo": "16",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "80",
            "SCIENCE": "74",
            "SST": "76",
            "LANG": "78"
        },
        {
            "AdmNo": "9688",
            "Student_name": "AYUSH MODI",
            "RollNo": "13",
            "Sec": "E",
            "ENGLISH": "71",
            "MATHEMATICS": "69",
            "SCIENCE": "55",
            "SST": "63",
            "LANG": "78"
        },
        {
            "AdmNo": "9689",
            "Student_name": "AYUSH NANDA",
            "RollNo": "11",
            "Sec": "D",
            "ENGLISH": "70",
            "MATHEMATICS": "59",
            "SCIENCE": "53",
            "SST": "47",
            "LANG": "75"
        },
        {
            "AdmNo": "9690",
            "Student_name": "KRUSHNA PRASAD DASH",
            "RollNo": "26",
            "Sec": "F",
            "ENGLISH": "74",
            "MATHEMATICS": "80",
            "SCIENCE": "74",
            "SST": "77",
            "LANG": "79"
        },
        {
            "AdmNo": "9691",
            "Student_name": "AVILIPSA SENAPATI",
            "RollNo": "15",
            "Sec": "C",
            "ENGLISH": "73",
            "MATHEMATICS": "74",
            "SCIENCE": "73",
            "SST": "75",
            "LANG": "77"
        },
        {
            "AdmNo": "9692",
            "Student_name": "AYUSH ROY",
            "RollNo": "5",
            "Sec": "B",
            "ENGLISH": "71",
            "MATHEMATICS": "71",
            "SCIENCE": "58",
            "SST": "58",
            "LANG": "72"
        },
        {
            "AdmNo": "9693",
            "Student_name": "ASAD MIRZA",
            "RollNo": "9",
            "Sec": "E",
            "ENGLISH": "75",
            "MATHEMATICS": "79",
            "SCIENCE": "70",
            "SST": "75",
            "LANG": "73"
        },
        {
            "AdmNo": "9694",
            "Student_name": "C ABHINEETH",
            "RollNo": "17",
            "Sec": "F",
            "ENGLISH": "78",
            "MATHEMATICS": "78",
            "SCIENCE": "74",
            "SST": "75",
            "LANG": "77"
        },
        {
            "AdmNo": "9695",
            "Student_name": "GIRIJA PRASAD",
            "RollNo": "22",
            "Sec": "C",
            "ENGLISH": "66",
            "MATHEMATICS": "37",
            "SCIENCE": "54",
            "SST": "51",
            "LANG": "71"
        },
        {
            "AdmNo": "9696",
            "Student_name": "KASMIN KAMAL NAYAK",
            "RollNo": "25",
            "Sec": "F",
            "ENGLISH": "78",
            "MATHEMATICS": "79",
            "SCIENCE": "75",
            "SST": "79",
            "LANG": "75"
        },
        {
            "AdmNo": "9698",
            "Student_name": "JASMIN MOHAPATRA",
            "RollNo": "17",
            "Sec": "D",
            "ENGLISH": "78",
            "MATHEMATICS": "78",
            "SCIENCE": "74",
            "SST": "74",
            "LANG": "80"
        },
        {
            "AdmNo": "9699",
            "Student_name": "DIBYA RANJAN DAS",
            "RollNo": "20",
            "Sec": "F",
            "ENGLISH": "71",
            "MATHEMATICS": "78",
            "SCIENCE": "74",
            "SST": "72",
            "LANG": "80"
        },
        {
            "AdmNo": "9700",
            "Student_name": "D HARSHITA",
            "RollNo": "20",
            "Sec": "C",
            "ENGLISH": "73",
            "MATHEMATICS": "55",
            "SCIENCE": "69",
            "SST": "57",
            "LANG": "72"
        },
        {
            "AdmNo": "9701",
            "Student_name": "AYUSMAN SAMAL",
            "RollNo": "11",
            "Sec": "A",
            "ENGLISH": "61",
            "MATHEMATICS": "37",
            "SCIENCE": "26",
            "SST": "54",
            "LANG": "60"
        },
        {
            "AdmNo": "9702",
            "Student_name": "AYUSH DAS",
            "RollNo": "10",
            "Sec": "D",
            "ENGLISH": "73",
            "MATHEMATICS": "78",
            "SCIENCE": "62",
            "SST": "67",
            "LANG": "72"
        },
        {
            "AdmNo": "9703",
            "Student_name": "GISPATI GYANENDRA",
            "RollNo": "16",
            "Sec": "D",
            "ENGLISH": "69",
            "MATHEMATICS": "62",
            "SCIENCE": "63",
            "SST": "67",
            "LANG": "75"
        },
        {
            "AdmNo": "9704",
            "Student_name": "AYUSHMAN KHADANGA",
            "RollNo": "10",
            "Sec": "A",
            "ENGLISH": "79",
            "MATHEMATICS": "57",
            "SCIENCE": "70",
            "SST": "63",
            "LANG": "79"
        },
        {
            "AdmNo": "9705",
            "Student_name": "PIYUSH BISWAL",
            "RollNo": "18",
            "Sec": "A",
            "ENGLISH": "44",
            "MATHEMATICS": "16",
            "SCIENCE": "27",
            "SST": "34",
            "LANG": "50"
        },
        {
            "AdmNo": "9706",
            "Student_name": "DEBANKITA SUBUDHI",
            "RollNo": "13",
            "Sec": "A",
            "ENGLISH": "69",
            "MATHEMATICS": "70",
            "SCIENCE": "46",
            "SST": "44",
            "LANG": "47"
        },
        {
            "AdmNo": "9708",
            "Student_name": "GAYATRI PATTNAIK",
            "RollNo": "8",
            "Sec": "B",
            "ENGLISH": "62",
            "MATHEMATICS": "25",
            "SCIENCE": "27",
            "SST": "50",
            "LANG": "77"
        },
        {
            "AdmNo": "9709",
            "Student_name": "ASHUTOSH SUBUDHI",
            "RollNo": "8",
            "Sec": "A",
            "ENGLISH": "66",
            "MATHEMATICS": "28",
            "SCIENCE": "40",
            "SST": "50",
            "LANG": "57"
        },
        {
            "AdmNo": "9710",
            "Student_name": "AFIFA SAMSI",
            "RollNo": "3",
            "Sec": "B",
            "ENGLISH": "69",
            "MATHEMATICS": "56",
            "SCIENCE": "55",
            "SST": "57",
            "LANG": "72"
        },
        {
            "AdmNo": "9711",
            "Student_name": "HOLIMA PRIYADARSHINI",
            "RollNo": "24",
            "Sec": "C",
            "ENGLISH": "71",
            "MATHEMATICS": "25",
            "SCIENCE": "38",
            "SST": "40",
            "LANG": "68"
        },
        {
            "AdmNo": "9712",
            "Student_name": "OM PRASAD SATAPATHY",
            "RollNo": "26",
            "Sec": "C",
            "ENGLISH": "60",
            "MATHEMATICS": "38",
            "SCIENCE": "24",
            "SST": "49",
            "LANG": "62"
        },
        {
            "AdmNo": "9713",
            "Student_name": "PRIYANSHU SAMANTARAY",
            "RollNo": "35",
            "Sec": "F",
            "ENGLISH": "78",
            "MATHEMATICS": "79",
            "SCIENCE": "76",
            "SST": "75",
            "LANG": "80"
        },
        {
            "AdmNo": "9714",
            "Student_name": "MOHAN SINGH",
            "RollNo": "26",
            "Sec": "E",
            "ENGLISH": "53",
            "MATHEMATICS": "27",
            "SCIENCE": "26",
            "SST": "36",
            "LANG": "46"
        },
        {
            "AdmNo": "9715",
            "Student_name": "PRAJAKTA NANDA",
            "RollNo": "22",
            "Sec": "D",
            "ENGLISH": "76",
            "MATHEMATICS": "AB",
            "SCIENCE": "70",
            "SST": "74",
            "LANG": "AB"
        },
        {
            "AdmNo": "9716",
            "Student_name": "OMM SANKAR MISHRA",
            "RollNo": "49",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "79",
            "SCIENCE": "75",
            "SST": "73",
            "LANG": "80"
        },
        {
            "AdmNo": "9718",
            "Student_name": "MAHEEP SINGH BHURJI",
            "RollNo": "24",
            "Sec": "E",
            "ENGLISH": "62",
            "MATHEMATICS": "34",
            "SCIENCE": "38",
            "SST": "51",
            "LANG": "64"
        },
        {
            "AdmNo": "9719",
            "Student_name": "PRAKRUTI LENKA",
            "RollNo": "21",
            "Sec": "A",
            "ENGLISH": "73",
            "MATHEMATICS": "72",
            "SCIENCE": "51",
            "SST": "69",
            "LANG": "70"
        },
        {
            "AdmNo": "9720",
            "Student_name": "PRAJAKTA MISHRA",
            "RollNo": "20",
            "Sec": "A",
            "ENGLISH": "72",
            "MATHEMATICS": "68",
            "SCIENCE": "62",
            "SST": "69",
            "LANG": "76"
        },
        {
            "AdmNo": "9721",
            "Student_name": "PRACHISMITA PRADHAN",
            "RollNo": "27",
            "Sec": "C",
            "ENGLISH": "71",
            "MATHEMATICS": "67",
            "SCIENCE": "56",
            "SST": "62",
            "LANG": "62"
        },
        {
            "AdmNo": "9722",
            "Student_name": "PRIYANSHI NAYAK",
            "RollNo": "31",
            "Sec": "E",
            "ENGLISH": "70",
            "MATHEMATICS": "38",
            "SCIENCE": "30",
            "SST": "59",
            "LANG": "55"
        },
        {
            "AdmNo": "9723",
            "Student_name": "PRATEEK SAHOO",
            "RollNo": "24",
            "Sec": "D",
            "ENGLISH": "65",
            "MATHEMATICS": "48",
            "SCIENCE": "40",
            "SST": "58",
            "LANG": "65"
        },
        {
            "AdmNo": "9724",
            "Student_name": "LOVELY PRIYADARSI PATRA",
            "RollNo": "20",
            "Sec": "D",
            "ENGLISH": "78",
            "MATHEMATICS": "77",
            "SCIENCE": "75",
            "SST": "73",
            "LANG": "80"
        },
        {
            "AdmNo": "9725",
            "Student_name": "LITTLE PRIYADARSI PATRA",
            "RollNo": "15",
            "Sec": "A",
            "ENGLISH": "77",
            "MATHEMATICS": "73",
            "SCIENCE": "69",
            "SST": "72",
            "LANG": "74"
        },
        {
            "AdmNo": "9726",
            "Student_name": "RAJASHREE BEHERA",
            "RollNo": "21",
            "Sec": "B",
            "ENGLISH": "68",
            "MATHEMATICS": "54",
            "SCIENCE": "51",
            "SST": "60",
            "LANG": "71"
        },
        {
            "AdmNo": "9727",
            "Student_name": "SUVRANSU SEKHAR",
            "RollNo": "39",
            "Sec": "D",
            "ENGLISH": "76",
            "MATHEMATICS": "79",
            "SCIENCE": "73",
            "SST": "76",
            "LANG": "78"
        },
        {
            "AdmNo": "9728",
            "Student_name": "PREETISMITA SAHU",
            "RollNo": "19",
            "Sec": "B",
            "ENGLISH": "70",
            "MATHEMATICS": "75",
            "SCIENCE": "68",
            "SST": "67",
            "LANG": "77"
        },
        {
            "AdmNo": "9730",
            "Student_name": "PIYUSH PATRA",
            "RollNo": "19",
            "Sec": "A",
            "ENGLISH": "44",
            "MATHEMATICS": "49",
            "SCIENCE": "49",
            "SST": "29",
            "LANG": "44"
        },
        {
            "AdmNo": "9731",
            "Student_name": "PRATYUS MISHRA",
            "RollNo": "31",
            "Sec": "F",
            "ENGLISH": "74",
            "MATHEMATICS": "79",
            "SCIENCE": "75",
            "SST": "67",
            "LANG": "78"
        },
        {
            "AdmNo": "9732",
            "Student_name": "MANASVI KEDIA",
            "RollNo": "25",
            "Sec": "E",
            "ENGLISH": "76",
            "MATHEMATICS": "70",
            "SCIENCE": "66",
            "SST": "72",
            "LANG": "78"
        },
        {
            "AdmNo": "9733",
            "Student_name": "PRATEEK MOHANTY",
            "RollNo": "30",
            "Sec": "F",
            "ENGLISH": "77",
            "MATHEMATICS": "78",
            "SCIENCE": "63",
            "SST": "66",
            "LANG": "78"
        },
        {
            "AdmNo": "9734",
            "Student_name": "SATYAJIT SAMANTRAY",
            "RollNo": "28",
            "Sec": "B",
            "ENGLISH": "65",
            "MATHEMATICS": "42",
            "SCIENCE": "39",
            "SST": "52",
            "LANG": "73"
        },
        {
            "AdmNo": "9735",
            "Student_name": "MOHIT KUMAR MOHANTY",
            "RollNo": "10",
            "Sec": "B",
            "ENGLISH": "61",
            "MATHEMATICS": "47",
            "SCIENCE": "41",
            "SST": "55",
            "LANG": "73"
        },
        {
            "AdmNo": "9736",
            "Student_name": "SHRUTI ROUTRAY",
            "RollNo": "32",
            "Sec": "D",
            "ENGLISH": "68",
            "MATHEMATICS": "58",
            "SCIENCE": "46",
            "SST": "46",
            "LANG": "75"
        },
        {
            "AdmNo": "9739",
            "Student_name": "RAMYAK RAY",
            "RollNo": "23",
            "Sec": "B",
            "ENGLISH": "72",
            "MATHEMATICS": "75",
            "SCIENCE": "71",
            "SST": "72",
            "LANG": "78"
        },
        {
            "AdmNo": "9740",
            "Student_name": "SHEETADRI KANUNGO",
            "RollNo": "30",
            "Sec": "B",
            "ENGLISH": "75",
            "MATHEMATICS": "57",
            "SCIENCE": "63",
            "SST": "77",
            "LANG": "78"
        },
        {
            "AdmNo": "9741",
            "Student_name": "SAMAHIT SWAIN",
            "RollNo": "26",
            "Sec": "A",
            "ENGLISH": "37",
            "MATHEMATICS": "19",
            "SCIENCE": "26",
            "SST": "42",
            "LANG": "41"
        },
        {
            "AdmNo": "9742",
            "Student_name": "SHREYANSHU DAS",
            "RollNo": "40",
            "Sec": "E",
            "ENGLISH": "65",
            "MATHEMATICS": "77",
            "SCIENCE": "74",
            "SST": "73",
            "LANG": "78"
        },
        {
            "AdmNo": "9743",
            "Student_name": "SANCHITA MOHANTY",
            "RollNo": "40",
            "Sec": "F",
            "ENGLISH": "69",
            "MATHEMATICS": "67",
            "SCIENCE": "54",
            "SST": "71",
            "LANG": "72"
        },
        {
            "AdmNo": "9744",
            "Student_name": "SAMIKHYA DAS",
            "RollNo": "30",
            "Sec": "D",
            "ENGLISH": "73",
            "MATHEMATICS": "71",
            "SCIENCE": "67",
            "SST": "64",
            "LANG": "77"
        },
        {
            "AdmNo": "9745",
            "Student_name": "SAMAIRA PATI",
            "RollNo": "29",
            "Sec": "D",
            "ENGLISH": "77",
            "MATHEMATICS": "70",
            "SCIENCE": "70",
            "SST": "77",
            "LANG": "80"
        },
        {
            "AdmNo": "9747",
            "Student_name": "SPANDAN MOHANTY",
            "RollNo": "45",
            "Sec": "F",
            "ENGLISH": "74",
            "MATHEMATICS": "73",
            "SCIENCE": "68",
            "SST": "71",
            "LANG": "74"
        },
        {
            "AdmNo": "9748",
            "Student_name": "RISHABH MISHRA",
            "RollNo": "35",
            "Sec": "C",
            "ENGLISH": "63",
            "MATHEMATICS": "69",
            "SCIENCE": "58",
            "SST": "59",
            "LANG": "71"
        },
        {
            "AdmNo": "9750",
            "Student_name": "RITUPARNA MISHRA",
            "RollNo": "24",
            "Sec": "A",
            "ENGLISH": "75",
            "MATHEMATICS": "71",
            "SCIENCE": "61",
            "SST": "59",
            "LANG": "71"
        },
        {
            "AdmNo": "9752",
            "Student_name": "SAMBHAB KUMAR",
            "RollNo": "27",
            "Sec": "B",
            "ENGLISH": "61",
            "MATHEMATICS": "25",
            "SCIENCE": "31",
            "SST": "46",
            "LANG": "58"
        },
        {
            "AdmNo": "9753",
            "Student_name": "PRIYAM GHOSH",
            "RollNo": "30",
            "Sec": "E",
            "ENGLISH": "69",
            "MATHEMATICS": "60",
            "SCIENCE": "66",
            "SST": "77",
            "LANG": "71"
        },
        {
            "AdmNo": "9754",
            "Student_name": "SHREYAN MISHRA",
            "RollNo": "33",
            "Sec": "B",
            "ENGLISH": "71",
            "MATHEMATICS": "70",
            "SCIENCE": "65",
            "SST": "65",
            "LANG": "76"
        },
        {
            "AdmNo": "9755",
            "Student_name": "SANSKRUTI MAHARATHI",
            "RollNo": "27",
            "Sec": "A",
            "ENGLISH": "77",
            "MATHEMATICS": "75",
            "SCIENCE": "62",
            "SST": "67",
            "LANG": "79"
        },
        {
            "AdmNo": "9757",
            "Student_name": "NISHITAA PATNAIK",
            "RollNo": "12",
            "Sec": "B",
            "ENGLISH": "48",
            "MATHEMATICS": "9",
            "SCIENCE": "43",
            "SST": "45",
            "LANG": "67"
        },
        {
            "AdmNo": "9758",
            "Student_name": "RUTURAJ PATTANAIK",
            "RollNo": "26",
            "Sec": "B",
            "ENGLISH": "68",
            "MATHEMATICS": "50",
            "SCIENCE": "52",
            "SST": "65",
            "LANG": "71"
        },
        {
            "AdmNo": "9759",
            "Student_name": "SHRUTI KHOWALA",
            "RollNo": "42",
            "Sec": "E",
            "ENGLISH": "76",
            "MATHEMATICS": "79",
            "SCIENCE": "75",
            "SST": "73",
            "LANG": "78"
        },
        {
            "AdmNo": "9760",
            "Student_name": "SHRADHA TRIPATHY",
            "RollNo": "31",
            "Sec": "B",
            "ENGLISH": "67",
            "MATHEMATICS": "43",
            "SCIENCE": "44",
            "SST": "64",
            "LANG": "65"
        },
        {
            "AdmNo": "9761",
            "Student_name": "SAMEEK MAHAPATRA",
            "RollNo": "38",
            "Sec": "E",
            "ENGLISH": "73",
            "MATHEMATICS": "65",
            "SCIENCE": "62",
            "SST": "71",
            "LANG": "70"
        },
        {
            "AdmNo": "9762",
            "Student_name": "SREYASH LENKA",
            "RollNo": "35",
            "Sec": "A",
            "ENGLISH": "68",
            "MATHEMATICS": "72",
            "SCIENCE": "65",
            "SST": "68",
            "LANG": "75"
        },
        {
            "AdmNo": "9764",
            "Student_name": "SHREEYA MAHAPATRA",
            "RollNo": "30",
            "Sec": "A",
            "ENGLISH": "72",
            "MATHEMATICS": "40",
            "SCIENCE": "49",
            "SST": "64",
            "LANG": "61"
        },
        {
            "AdmNo": "9765",
            "Student_name": "SAI SASWAT NANDA",
            "RollNo": "37",
            "Sec": "E",
            "ENGLISH": "67",
            "MATHEMATICS": "74",
            "SCIENCE": "60",
            "SST": "60",
            "LANG": "72"
        },
        {
            "AdmNo": "9766",
            "Student_name": "SAI DHEEMAN PATTANAYAK",
            "RollNo": "37",
            "Sec": "C",
            "ENGLISH": "76",
            "MATHEMATICS": "70",
            "SCIENCE": "76",
            "SST": "75",
            "LANG": "80"
        },
        {
            "AdmNo": "9767",
            "Student_name": "SABNAM DAS",
            "RollNo": "27",
            "Sec": "D",
            "ENGLISH": "74",
            "MATHEMATICS": "74",
            "SCIENCE": "69",
            "SST": "78",
            "LANG": "78"
        },
        {
            "AdmNo": "9768",
            "Student_name": "SHASWAT SUBUDHI",
            "RollNo": "29",
            "Sec": "A",
            "ENGLISH": "67",
            "MATHEMATICS": "55",
            "SCIENCE": "53",
            "SST": "57",
            "LANG": "68"
        },
        {
            "AdmNo": "9769",
            "Student_name": "VARUN MISHRA",
            "RollNo": "48",
            "Sec": "F",
            "ENGLISH": "78",
            "MATHEMATICS": "79",
            "SCIENCE": "79",
            "SST": "77",
            "LANG": "80"
        },
        {
            "AdmNo": "9770",
            "Student_name": "SUSHREE BAIVABI",
            "RollNo": "40",
            "Sec": "B",
            "ENGLISH": "72",
            "MATHEMATICS": "69",
            "SCIENCE": "68",
            "SST": "72",
            "LANG": "79"
        },
        {
            "AdmNo": "9771",
            "Student_name": "SRUTI MOHANTY",
            "RollNo": "43",
            "Sec": "E",
            "ENGLISH": "74",
            "MATHEMATICS": "68",
            "SCIENCE": "66",
            "SST": "68",
            "LANG": "71"
        },
        {
            "AdmNo": "9772",
            "Student_name": "SAI RAUNAK PATRA",
            "RollNo": "38",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "67",
            "SCIENCE": "57",
            "SST": "71",
            "LANG": "79"
        },
        {
            "AdmNo": "9773",
            "Student_name": "SIBA PRASAD MUDULI",
            "RollNo": "33",
            "Sec": "D",
            "ENGLISH": "74",
            "MATHEMATICS": "53",
            "SCIENCE": "59",
            "SST": "71",
            "LANG": "78"
        },
        {
            "AdmNo": "9774",
            "Student_name": "SUDIKSHYA SONALIKA",
            "RollNo": "48",
            "Sec": "C",
            "ENGLISH": "72",
            "MATHEMATICS": "71",
            "SCIENCE": "61",
            "SST": "73",
            "LANG": "68"
        },
        {
            "AdmNo": "9775",
            "Student_name": "SIPRA MISHRA",
            "RollNo": "39",
            "Sec": "C",
            "ENGLISH": "65",
            "MATHEMATICS": "48",
            "SCIENCE": "47",
            "SST": "62",
            "LANG": "76"
        },
        {
            "AdmNo": "9777",
            "Student_name": "SATWIK MISHRA",
            "RollNo": "41",
            "Sec": "F",
            "ENGLISH": "70",
            "MATHEMATICS": "71",
            "SCIENCE": "53",
            "SST": "56",
            "LANG": "63"
        },
        {
            "AdmNo": "9778",
            "Student_name": "SOUBHAGYA SWASTIK DHAL",
            "RollNo": "40",
            "Sec": "C",
            "ENGLISH": "73",
            "MATHEMATICS": "66",
            "SCIENCE": "54",
            "SST": "65",
            "LANG": "75"
        },
        {
            "AdmNo": "9780",
            "Student_name": "TRINAYAN ADITYA",
            "RollNo": "43",
            "Sec": "D",
            "ENGLISH": "61",
            "MATHEMATICS": "41",
            "SCIENCE": "45",
            "SST": "52",
            "LANG": "75"
        },
        {
            "AdmNo": "9781",
            "Student_name": "SNEHA MALLICK",
            "RollNo": "44",
            "Sec": "F",
            "ENGLISH": "78",
            "MATHEMATICS": "74",
            "SCIENCE": "74",
            "SST": "73",
            "LANG": "78"
        },
        {
            "AdmNo": "9782",
            "Student_name": "SUBHRAKANT SINGH",
            "RollNo": "39",
            "Sec": "B",
            "ENGLISH": "65",
            "MATHEMATICS": "26",
            "SCIENCE": "39",
            "SST": "59",
            "LANG": "75"
        },
        {
            "AdmNo": "9783",
            "Student_name": "SWETA PADMA ROUT",
            "RollNo": "41",
            "Sec": "B",
            "ENGLISH": "72",
            "MATHEMATICS": "58",
            "SCIENCE": "63",
            "SST": "72",
            "LANG": "78"
        },
        {
            "AdmNo": "9784",
            "Student_name": "PRIYANSHU MOHANTY",
            "RollNo": "34",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "63",
            "SCIENCE": "75",
            "SST": "70",
            "LANG": "79"
        },
        {
            "AdmNo": "9786",
            "Student_name": "SRUSTI SAMIKSHYA",
            "RollNo": "37",
            "Sec": "A",
            "ENGLISH": "77",
            "MATHEMATICS": "44",
            "SCIENCE": "59",
            "SST": "65",
            "LANG": "69"
        },
        {
            "AdmNo": "9788",
            "Student_name": "TANUSH MISHRA",
            "RollNo": "42",
            "Sec": "D",
            "ENGLISH": "69",
            "MATHEMATICS": "51",
            "SCIENCE": "54",
            "SST": "62",
            "LANG": "76"
        },
        {
            "AdmNo": "9789",
            "Student_name": "SULAGNA MISHRA",
            "RollNo": "37",
            "Sec": "D",
            "ENGLISH": "68",
            "MATHEMATICS": "66",
            "SCIENCE": "73",
            "SST": "72",
            "LANG": "79"
        },
        {
            "AdmNo": "9790",
            "Student_name": "SOHAM SAIPRASAD ROUT",
            "RollNo": "35",
            "Sec": "B",
            "ENGLISH": "66",
            "MATHEMATICS": "48",
            "SCIENCE": "40",
            "SST": "55",
            "LANG": "64"
        },
        {
            "AdmNo": "9791",
            "Student_name": "SRIYALI DAS",
            "RollNo": "38",
            "Sec": "B",
            "ENGLISH": "74",
            "MATHEMATICS": "79",
            "SCIENCE": "72",
            "SST": "77",
            "LANG": "80"
        },
        {
            "AdmNo": "9793",
            "Student_name": "SUSHOBHAN GHOSH",
            "RollNo": "39",
            "Sec": "A",
            "ENGLISH": "64",
            "MATHEMATICS": "64",
            "SCIENCE": "42",
            "SST": "52",
            "LANG": "70"
        },
        {
            "AdmNo": "9794",
            "Student_name": "TANISHA DASH",
            "RollNo": "41",
            "Sec": "A",
            "ENGLISH": "74",
            "MATHEMATICS": "70",
            "SCIENCE": "67",
            "SST": "73",
            "LANG": "75"
        },
        {
            "AdmNo": "9795",
            "Student_name": "SOURYAA DAS",
            "RollNo": "41",
            "Sec": "C",
            "ENGLISH": "77",
            "MATHEMATICS": "71",
            "SCIENCE": "73",
            "SST": "74",
            "LANG": "80"
        },
        {
            "AdmNo": "9796",
            "Student_name": "SURYANSHU GRAHACHARYA",
            "RollNo": "38",
            "Sec": "D",
            "ENGLISH": "71",
            "MATHEMATICS": "79",
            "SCIENCE": "75",
            "SST": "69",
            "LANG": "80"
        },
        {
            "AdmNo": "9797",
            "Student_name": "SWAPNA SALINI ROUT",
            "RollNo": "43",
            "Sec": "C",
            "ENGLISH": "73",
            "MATHEMATICS": "49",
            "SCIENCE": "49",
            "SST": "44",
            "LANG": "70"
        },
        {
            "AdmNo": "9799",
            "Student_name": "YOGESH MOHANTY",
            "RollNo": "42",
            "Sec": "A",
            "ENGLISH": "53",
            "MATHEMATICS": "63",
            "SCIENCE": "49",
            "SST": "43",
            "LANG": "52"
        },
        {
            "AdmNo": "9800",
            "Student_name": "ADITYA MALLICK",
            "RollNo": "1",
            "Sec": "B",
            "ENGLISH": "66",
            "MATHEMATICS": "66",
            "SCIENCE": "61",
            "SST": "63",
            "LANG": "72"
        },
        {
            "AdmNo": "9801",
            "Student_name": "SWAGAT PRADHAN",
            "RollNo": "47",
            "Sec": "F",
            "ENGLISH": "74",
            "MATHEMATICS": "72",
            "SCIENCE": "56",
            "SST": "69",
            "LANG": "74"
        },
        {
            "AdmNo": "9802",
            "Student_name": "SUKANYA SWAGATIKA",
            "RollNo": "46",
            "Sec": "E",
            "ENGLISH": "54",
            "MATHEMATICS": "33",
            "SCIENCE": "31",
            "SST": "46",
            "LANG": "62"
        },
        {
            "AdmNo": "9804",
            "Student_name": "SOUMYA SURAJ TRIPATHY",
            "RollNo": "36",
            "Sec": "B",
            "ENGLISH": "70",
            "MATHEMATICS": "63",
            "SCIENCE": "71",
            "SST": "73",
            "LANG": "79"
        },
        {
            "AdmNo": "10122",
            "Student_name": "ADITYA KARTIK PARIJA",
            "RollNo": "2",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "72",
            "SCIENCE": "63",
            "SST": "67",
            "LANG": "76"
        },
        {
            "AdmNo": "10123",
            "Student_name": "AISHWARYA PRUSTY",
            "RollNo": "3",
            "Sec": "A",
            "ENGLISH": "74",
            "MATHEMATICS": "66",
            "SCIENCE": "70",
            "SST": "65",
            "LANG": "78"
        },
        {
            "AdmNo": "10124",
            "Student_name": "AMAN AGARWAL",
            "RollNo": "14",
            "Sec": "E",
            "ENGLISH": "72",
            "MATHEMATICS": "72",
            "SCIENCE": "65",
            "SST": "75",
            "LANG": "75"
        },
        {
            "AdmNo": "10126",
            "Student_name": "ANKIT PUJARI",
            "RollNo": "12",
            "Sec": "C",
            "ENGLISH": "66",
            "MATHEMATICS": "59",
            "SCIENCE": "58",
            "SST": "64",
            "LANG": "65"
        },
        {
            "AdmNo": "10127",
            "Student_name": "ARMAAN KUMAR",
            "RollNo": "9",
            "Sec": "D",
            "ENGLISH": "54",
            "MATHEMATICS": "21",
            "SCIENCE": "17",
            "SST": "28",
            "LANG": "58"
        },
        {
            "AdmNo": "10128",
            "Student_name": "AUROSIS DAS",
            "RollNo": "10",
            "Sec": "E",
            "ENGLISH": "71",
            "MATHEMATICS": "69",
            "SCIENCE": "55",
            "SST": "65",
            "LANG": "73"
        },
        {
            "AdmNo": "10129",
            "Student_name": "ARPITA LENKA",
            "RollNo": "8",
            "Sec": "E",
            "ENGLISH": "66",
            "MATHEMATICS": "36",
            "SCIENCE": "38",
            "SST": "52",
            "LANG": "58"
        },
        {
            "AdmNo": "10130",
            "Student_name": "AYUSHA DAS",
            "RollNo": "12",
            "Sec": "D",
            "ENGLISH": "77",
            "MATHEMATICS": "73",
            "SCIENCE": "78",
            "SST": "75",
            "LANG": "80"
        },
        {
            "AdmNo": "10131",
            "Student_name": "AYUSH DAS",
            "RollNo": "16",
            "Sec": "C",
            "ENGLISH": "60",
            "MATHEMATICS": "39",
            "SCIENCE": "48",
            "SST": "54",
            "LANG": "45"
        },
        {
            "AdmNo": "10132",
            "Student_name": "BIBHUDUTTA KHUNTIA",
            "RollNo": "15",
            "Sec": "F",
            "ENGLISH": "79",
            "MATHEMATICS": "73",
            "SCIENCE": "68",
            "SST": "76",
            "LANG": "79"
        },
        {
            "AdmNo": "10133",
            "Student_name": "CHETANASHREE PATNAIK",
            "RollNo": "12",
            "Sec": "A",
            "ENGLISH": "25",
            "MATHEMATICS": "15",
            "SCIENCE": "16",
            "SST": "32",
            "LANG": "50"
        },
        {
            "AdmNo": "10134",
            "Student_name": "DEBANSH SWAROOP",
            "RollNo": "15",
            "Sec": "D",
            "ENGLISH": "64",
            "MATHEMATICS": "14",
            "SCIENCE": "45",
            "SST": "55",
            "LANG": "66"
        },
        {
            "AdmNo": "10135",
            "Student_name": "DEVANSHI RAO",
            "RollNo": "16",
            "Sec": "E",
            "ENGLISH": "65",
            "MATHEMATICS": "37",
            "SCIENCE": "41",
            "SST": "62",
            "LANG": "65"
        },
        {
            "AdmNo": "10136",
            "Student_name": "DIBYAJEET MOHANTY",
            "RollNo": "21",
            "Sec": "F",
            "ENGLISH": "76",
            "MATHEMATICS": "75",
            "SCIENCE": "73",
            "SST": "72",
            "LANG": "76"
        },
        {
            "AdmNo": "10137",
            "Student_name": "HRISHITA DEY",
            "RollNo": "23",
            "Sec": "F",
            "ENGLISH": "71",
            "MATHEMATICS": "48",
            "SCIENCE": "62",
            "SST": "70",
            "LANG": "77"
        },
        {
            "AdmNo": "10138",
            "Student_name": "JAYESH DAS",
            "RollNo": "24",
            "Sec": "F",
            "ENGLISH": "78",
            "MATHEMATICS": "78",
            "SCIENCE": "71",
            "SST": "79",
            "LANG": "78"
        },
        {
            "AdmNo": "10139",
            "Student_name": "KRUSHNA SAMBHAV MOHANTY",
            "RollNo": "23",
            "Sec": "E",
            "ENGLISH": "61",
            "MATHEMATICS": "53",
            "SCIENCE": "49",
            "SST": "54",
            "LANG": "64"
        },
        {
            "AdmNo": "10140",
            "Student_name": "MANISHA SAHOO",
            "RollNo": "21",
            "Sec": "D",
            "ENGLISH": "68",
            "MATHEMATICS": "48",
            "SCIENCE": "60",
            "SST": "69",
            "LANG": "73"
        },
        {
            "AdmNo": "10141",
            "Student_name": "MONTY MILAN BISWAL",
            "RollNo": "27",
            "Sec": "F",
            "ENGLISH": "70",
            "MATHEMATICS": "75",
            "SCIENCE": "59",
            "SST": "65",
            "LANG": "60"
        },
        {
            "AdmNo": "10142",
            "Student_name": "NATASHA NAYAK",
            "RollNo": "11",
            "Sec": "B",
            "ENGLISH": "70",
            "MATHEMATICS": "40",
            "SCIENCE": "51",
            "SST": "61",
            "LANG": "79"
        },
        {
            "AdmNo": "10143",
            "Student_name": "NISHANT PRUSTY",
            "RollNo": "16",
            "Sec": "A",
            "ENGLISH": "71",
            "MATHEMATICS": "63",
            "SCIENCE": "36",
            "SST": "60",
            "LANG": "74"
        },
        {
            "AdmNo": "10144",
            "Student_name": "PRIYABRATA DAS",
            "RollNo": "33",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "80",
            "SCIENCE": "64",
            "SST": "76",
            "LANG": "76"
        },
        {
            "AdmNo": "10145",
            "Student_name": "PRATIKSHYA MOHANTY",
            "RollNo": "31",
            "Sec": "C",
            "ENGLISH": "70",
            "MATHEMATICS": "69",
            "SCIENCE": "63",
            "SST": "61",
            "LANG": "65"
        },
        {
            "AdmNo": "10146",
            "Student_name": "PRAGYANA PARAMITA SINGH",
            "RollNo": "16",
            "Sec": "B",
            "ENGLISH": "47",
            "MATHEMATICS": "42",
            "SCIENCE": "22",
            "SST": "27",
            "LANG": "60"
        },
        {
            "AdmNo": "10147",
            "Student_name": "PREETIPARNA RATH",
            "RollNo": "22",
            "Sec": "A",
            "ENGLISH": "78",
            "MATHEMATICS": "78",
            "SCIENCE": "71",
            "SST": "77",
            "LANG": "79"
        },
        {
            "AdmNo": "10148",
            "Student_name": "ROSHAN KUMAR SAHOO",
            "RollNo": "34",
            "Sec": "E",
            "ENGLISH": "75",
            "MATHEMATICS": "54",
            "SCIENCE": "51",
            "SST": "61",
            "LANG": "78"
        },
        {
            "AdmNo": "10149",
            "Student_name": "SAI PRATIM MISHRA",
            "RollNo": "28",
            "Sec": "D",
            "ENGLISH": "56",
            "MATHEMATICS": "46",
            "SCIENCE": "41",
            "SST": "43",
            "LANG": "60"
        },
        {
            "AdmNo": "10151",
            "Student_name": "SASWAT SUBHADARSI PATTNAIK",
            "RollNo": "28",
            "Sec": "A",
            "ENGLISH": "69",
            "MATHEMATICS": "62",
            "SCIENCE": "62",
            "SST": "60",
            "LANG": "66"
        },
        {
            "AdmNo": "10152",
            "Student_name": "SATYA SUNDAR SAHOO",
            "RollNo": "39",
            "Sec": "E",
            "ENGLISH": "53",
            "MATHEMATICS": "35",
            "SCIENCE": "33",
            "SST": "51",
            "LANG": "61"
        },
        {
            "AdmNo": "10153",
            "Student_name": "SOMESH KUMAR JENA",
            "RollNo": "33",
            "Sec": "A",
            "ENGLISH": "71",
            "MATHEMATICS": "72",
            "SCIENCE": "66",
            "SST": "71",
            "LANG": "77"
        },
        {
            "AdmNo": "10154",
            "Student_name": "SWIKRUTI PATNAIK",
            "RollNo": "40",
            "Sec": "D",
            "ENGLISH": "65",
            "MATHEMATICS": "32",
            "SCIENCE": "47",
            "SST": "66",
            "LANG": "65"
        },
        {
            "AdmNo": "10155",
            "Student_name": "TANMAYA NAYAK",
            "RollNo": "41",
            "Sec": "D",
            "ENGLISH": "71",
            "MATHEMATICS": "69",
            "SCIENCE": "63",
            "SST": "70",
            "LANG": "79"
        },
        {
            "AdmNo": "10156",
            "Student_name": "SRUSHTI DAS",
            "RollNo": "42",
            "Sec": "C",
            "ENGLISH": "67",
            "MATHEMATICS": "15",
            "SCIENCE": "32",
            "SST": "44",
            "LANG": "76"
        },
        {
            "AdmNo": "10157",
            "Student_name": "UMESH KUMAR RANA",
            "RollNo": "43",
            "Sec": "B",
            "ENGLISH": "72",
            "MATHEMATICS": "40",
            "SCIENCE": "43",
            "SST": "74",
            "LANG": "76"
        },
        {
            "AdmNo": "10158",
            "Student_name": "SOMANSU PADHI",
            "RollNo": "46",
            "Sec": "C",
            "ENGLISH": "68",
            "MATHEMATICS": "47",
            "SCIENCE": "42",
            "SST": "69",
            "LANG": "59"
        },
        {
            "AdmNo": "10184",
            "Student_name": "PIYUSH DAS",
            "RollNo": "29",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "74",
            "SCIENCE": "59",
            "SST": "72",
            "LANG": "75"
        },
        {
            "AdmNo": "10216",
            "Student_name": "ANURAG SATAPATHY",
            "RollNo": "13",
            "Sec": "C",
            "ENGLISH": "64",
            "MATHEMATICS": "63",
            "SCIENCE": "64",
            "SST": "58",
            "LANG": "71"
        },
        {
            "AdmNo": "10222",
            "Student_name": "SRIHARI DAS",
            "RollNo": "36",
            "Sec": "A",
            "ENGLISH": "51",
            "MATHEMATICS": "26",
            "SCIENCE": "21",
            "SST": "39",
            "LANG": "62"
        },
        {
            "AdmNo": "10229",
            "Student_name": "SHANVI PRIYADARSHINI",
            "RollNo": "29",
            "Sec": "B",
            "ENGLISH": "68",
            "MATHEMATICS": "50",
            "SCIENCE": "54",
            "SST": "60",
            "LANG": "78"
        },
        {
            "AdmNo": "10672",
            "Student_name": "HARSHIT RITAM",
            "RollNo": "22",
            "Sec": "F",
            "ENGLISH": "76",
            "MATHEMATICS": "73",
            "SCIENCE": "66",
            "SST": "74",
            "LANG": "77"
        },
        {
            "AdmNo": "10673",
            "Student_name": "PURNIMA SANGRAMSINGH",
            "RollNo": "33",
            "Sec": "C",
            "ENGLISH": "79",
            "MATHEMATICS": "74",
            "SCIENCE": "66",
            "SST": "75",
            "LANG": "78"
        },
        {
            "AdmNo": "10945",
            "Student_name": "ABHIPSHA MOHANTY",
            "RollNo": "2",
            "Sec": "E",
            "ENGLISH": "76",
            "MATHEMATICS": "76",
            "SCIENCE": "77",
            "SST": "78",
            "LANG": "79"
        },
        {
            "AdmNo": "10980",
            "Student_name": "SUBHASHREE PRADHAN",
            "RollNo": "36",
            "Sec": "D",
            "ENGLISH": "74",
            "MATHEMATICS": "47",
            "SCIENCE": "30",
            "SST": "61",
            "LANG": "78"
        },
        {
            "AdmNo": "10981",
            "Student_name": "SURYA NARAYAN PANDA",
            "RollNo": "38",
            "Sec": "A",
            "ENGLISH": "69",
            "MATHEMATICS": "75",
            "SCIENCE": "65",
            "SST": "67",
            "LANG": "72"
        },
        {
            "AdmNo": "10982",
            "Student_name": "SWAHUM ROUT",
            "RollNo": "40",
            "Sec": "A",
            "ENGLISH": "77",
            "MATHEMATICS": "72",
            "SCIENCE": "70",
            "SST": "66",
            "LANG": "75"
        },
        {
            "AdmNo": "10983",
            "Student_name": "ASISH KUMAR PATRA",
            "RollNo": "13",
            "Sec": "F",
            "ENGLISH": "71",
            "MATHEMATICS": "72",
            "SCIENCE": "58",
            "SST": "77",
            "LANG": "71"
        },
        {
            "AdmNo": "10985",
            "Student_name": "VARSHA PRIYADARSHINI",
            "RollNo": "47",
            "Sec": "E",
            "ENGLISH": "75",
            "MATHEMATICS": "63",
            "SCIENCE": "63",
            "SST": "61",
            "LANG": "59"
        },
        {
            "AdmNo": "10986",
            "Student_name": "ROHIT KUMAR MISHRA",
            "RollNo": "25",
            "Sec": "A",
            "ENGLISH": "67",
            "MATHEMATICS": "60",
            "SCIENCE": "63",
            "SST": "64",
            "LANG": "74"
        },
        {
            "AdmNo": "10987",
            "Student_name": "OMM PRAKASH PATTNAIK",
            "RollNo": "13",
            "Sec": "B",
            "ENGLISH": "74",
            "MATHEMATICS": "75",
            "SCIENCE": "74",
            "SST": "74",
            "LANG": "79"
        },
        {
            "AdmNo": "10989",
            "Student_name": "RISHITA DASH",
            "RollNo": "37",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "79",
            "SCIENCE": "75",
            "SST": "71",
            "LANG": "80"
        },
        {
            "AdmNo": "10990",
            "Student_name": "RONIT PATTANAYAK",
            "RollNo": "24",
            "Sec": "B",
            "ENGLISH": "72",
            "MATHEMATICS": "76",
            "SCIENCE": "76",
            "SST": "76",
            "LANG": "79"
        },
        {
            "AdmNo": "10991",
            "Student_name": "PRATISHA BISWAL",
            "RollNo": "17",
            "Sec": "B",
            "ENGLISH": "74",
            "MATHEMATICS": "70",
            "SCIENCE": "59",
            "SST": "64",
            "LANG": "78"
        },
        {
            "AdmNo": "10992",
            "Student_name": "APURVA APARUPA DASH",
            "RollNo": "14",
            "Sec": "C",
            "ENGLISH": "76",
            "MATHEMATICS": "71",
            "SCIENCE": "70",
            "SST": "74",
            "LANG": "78"
        },
        {
            "AdmNo": "10993",
            "Student_name": "DIBVYANSU SWAIN",
            "RollNo": "14",
            "Sec": "A",
            "ENGLISH": "73",
            "MATHEMATICS": "74",
            "SCIENCE": "69",
            "SST": "74",
            "LANG": "73"
        },
        {
            "AdmNo": "10994",
            "Student_name": "BAIBHAV AVISEK",
            "RollNo": "44",
            "Sec": "B",
            "ENGLISH": "69",
            "MATHEMATICS": "51",
            "SCIENCE": "52",
            "SST": "63",
            "LANG": "70"
        },
        {
            "AdmNo": "10995",
            "Student_name": "PRABHUSHAKTI PATTNAIK",
            "RollNo": "15",
            "Sec": "B",
            "ENGLISH": "36",
            "MATHEMATICS": "9",
            "SCIENCE": "22",
            "SST": "38",
            "LANG": "28"
        },
        {
            "AdmNo": "10996",
            "Student_name": "PRATYUSHA PRIYADARSINI",
            "RollNo": "25",
            "Sec": "D",
            "ENGLISH": "76",
            "MATHEMATICS": "74",
            "SCIENCE": "57",
            "SST": "74",
            "LANG": "78"
        },
        {
            "AdmNo": "10997",
            "Student_name": "SHRUTI SHREEYAM",
            "RollNo": "42",
            "Sec": "F",
            "ENGLISH": "64",
            "MATHEMATICS": "71",
            "SCIENCE": "53",
            "SST": "64",
            "LANG": "62"
        },
        {
            "AdmNo": "10998",
            "Student_name": "BASUDEV MOHAPATRA",
            "RollNo": "14",
            "Sec": "F",
            "ENGLISH": "76",
            "MATHEMATICS": "80",
            "SCIENCE": "77",
            "SST": "80",
            "LANG": "79"
        },
        {
            "AdmNo": "10999",
            "Student_name": "ROSHNI BHUBANESWARI SWAIN",
            "RollNo": "26",
            "Sec": "D",
            "ENGLISH": "75",
            "MATHEMATICS": "70",
            "SCIENCE": "65",
            "SST": "76",
            "LANG": "78"
        },
        {
            "AdmNo": "11000",
            "Student_name": "DIVESH KUMAR BHANJA",
            "RollNo": "21",
            "Sec": "C",
            "ENGLISH": "73",
            "MATHEMATICS": "55",
            "SCIENCE": "53",
            "SST": "37",
            "LANG": "73"
        },
        {
            "AdmNo": "11001",
            "Student_name": "ADWITI KAR",
            "RollNo": "3",
            "Sec": "D",
            "ENGLISH": "73",
            "MATHEMATICS": "72",
            "SCIENCE": "66",
            "SST": "76",
            "LANG": "76"
        },
        {
            "AdmNo": "11002",
            "Student_name": "ROSHAN KUMAR PRUSTY",
            "RollNo": "25",
            "Sec": "B",
            "ENGLISH": "68",
            "MATHEMATICS": "66",
            "SCIENCE": "57",
            "SST": "69",
            "LANG": "75"
        },
        {
            "AdmNo": "11003",
            "Student_name": "ABHILIPSA PATRA",
            "RollNo": "1",
            "Sec": "E",
            "ENGLISH": "65",
            "MATHEMATICS": "67",
            "SCIENCE": "60",
            "SST": "64",
            "LANG": "69"
        },
        {
            "AdmNo": "11005",
            "Student_name": "KAIBALYA PRASAD POTHAL",
            "RollNo": "25",
            "Sec": "C",
            "ENGLISH": "71",
            "MATHEMATICS": "44",
            "SCIENCE": "56",
            "SST": "65",
            "LANG": "73"
        },
        {
            "AdmNo": "11006",
            "Student_name": "RAJESH KUMAR SAHU",
            "RollNo": "22",
            "Sec": "B",
            "ENGLISH": "57",
            "MATHEMATICS": "27",
            "SCIENCE": "29",
            "SST": "46",
            "LANG": "69"
        },
        {
            "AdmNo": "11007",
            "Student_name": "BIBEK MOHANTY",
            "RollNo": "7",
            "Sec": "B",
            "ENGLISH": "75",
            "MATHEMATICS": "72",
            "SCIENCE": "77",
            "SST": "73",
            "LANG": "78"
        },
        {
            "AdmNo": "11008",
            "Student_name": "ARPIT ABHIGYAN PARIDA",
            "RollNo": "4",
            "Sec": "B",
            "ENGLISH": "62",
            "MATHEMATICS": "67",
            "SCIENCE": "51",
            "SST": "57",
            "LANG": "73"
        },
        {
            "AdmNo": "11009",
            "Student_name": "SOUMYA RANJAN MALLICK",
            "RollNo": "34",
            "Sec": "A",
            "ENGLISH": "68",
            "MATHEMATICS": "64",
            "SCIENCE": "58",
            "SST": "64",
            "LANG": "71"
        },
        {
            "AdmNo": "11113",
            "Student_name": "ASIM SOURAV RATH",
            "RollNo": "12",
            "Sec": "F",
            "ENGLISH": "72",
            "MATHEMATICS": "63",
            "SCIENCE": "66",
            "SST": "65",
            "LANG": "80"
        },
        {
            "AdmNo": "11117",
            "Student_name": "AYUSMAN MOHANTY",
            "RollNo": "6",
            "Sec": "B",
            "ENGLISH": "71",
            "MATHEMATICS": "71",
            "SCIENCE": "55",
            "SST": "58",
            "LANG": "73"
        },
        {
            "AdmNo": "11666",
            "Student_name": "ADITI RAY",
            "RollNo": "5",
            "Sec": "C",
            "ENGLISH": "72",
            "MATHEMATICS": "69",
            "SCIENCE": "65",
            "SST": "69",
            "LANG": "72"
        },
        {
            "AdmNo": "11667",
            "Student_name": "ABHIPSA NANDA",
            "RollNo": "3",
            "Sec": "E",
            "ENGLISH": "76",
            "MATHEMATICS": "73",
            "SCIENCE": "75",
            "SST": "79",
            "LANG": "73"
        },
        {
            "AdmNo": "11669",
            "Student_name": "ANKIT PRITAM MALLICK",
            "RollNo": "11",
            "Sec": "C",
            "ENGLISH": "59",
            "MATHEMATICS": "42",
            "SCIENCE": "38",
            "SST": "43",
            "LANG": "55"
        },
        {
            "AdmNo": "11670",
            "Student_name": "ANKITA PANDA",
            "RollNo": "6",
            "Sec": "E",
            "ENGLISH": "68",
            "MATHEMATICS": "22",
            "SCIENCE": "25",
            "SST": "52",
            "LANG": "65"
        },
        {
            "AdmNo": "11671",
            "Student_name": "BARIDHI PATRA",
            "RollNo": "14",
            "Sec": "D",
            "ENGLISH": "66",
            "MATHEMATICS": "18",
            "SCIENCE": "30",
            "SST": "55",
            "LANG": "70"
        },
        {
            "AdmNo": "11672",
            "Student_name": "ARPITA DAS",
            "RollNo": "11",
            "Sec": "F",
            "ENGLISH": "74",
            "MATHEMATICS": "76",
            "SCIENCE": "68",
            "SST": "69",
            "LANG": "73"
        },
        {
            "AdmNo": "11673",
            "Student_name": "KRRISH MAHAPATRA",
            "RollNo": "19",
            "Sec": "D",
            "ENGLISH": "60",
            "MATHEMATICS": "21",
            "SCIENCE": "35",
            "SST": "46",
            "LANG": "54"
        },
        {
            "AdmNo": "11675",
            "Student_name": "PRATYUSH KUMAR MOHAPATRA",
            "RollNo": "32",
            "Sec": "C",
            "ENGLISH": "76",
            "MATHEMATICS": "76",
            "SCIENCE": "69",
            "SST": "75",
            "LANG": "74"
        },
        {
            "AdmNo": "11676",
            "Student_name": "PREESHA PATTNAIK",
            "RollNo": "18",
            "Sec": "B",
            "ENGLISH": "77",
            "MATHEMATICS": "70",
            "SCIENCE": "67",
            "SST": "71",
            "LANG": "77"
        },
        {
            "AdmNo": "11677",
            "Student_name": "PRATYUSH KUMAR SWAIN",
            "RollNo": "32",
            "Sec": "F",
            "ENGLISH": "78",
            "MATHEMATICS": "80",
            "SCIENCE": "77",
            "SST": "78",
            "LANG": "80"
        },
        {
            "AdmNo": "11679",
            "Student_name": "GULL SHARMA",
            "RollNo": "18",
            "Sec": "E",
            "ENGLISH": "65",
            "MATHEMATICS": "66",
            "SCIENCE": "29",
            "SST": "49",
            "LANG": "70"
        },
        {
            "AdmNo": "11680",
            "Student_name": "SHRESTHA MOHANTY",
            "RollNo": "32",
            "Sec": "B",
            "ENGLISH": "76",
            "MATHEMATICS": "80",
            "SCIENCE": "76",
            "SST": "77",
            "LANG": "76"
        },
        {
            "AdmNo": "11681",
            "Student_name": "SHREYA DIXIT",
            "RollNo": "32",
            "Sec": "A",
            "ENGLISH": "64",
            "MATHEMATICS": "46",
            "SCIENCE": "35",
            "SST": "57",
            "LANG": "73"
        },
        {
            "AdmNo": "11682",
            "Student_name": "SHRESTHA SHARMA",
            "RollNo": "31",
            "Sec": "A",
            "ENGLISH": "76",
            "MATHEMATICS": "38",
            "SCIENCE": "41",
            "SST": "64",
            "LANG": "72"
        },
        {
            "AdmNo": "11683",
            "Student_name": "N SHREYA SUBHADARSHINI",
            "RollNo": "28",
            "Sec": "E",
            "ENGLISH": "69",
            "MATHEMATICS": "44",
            "SCIENCE": "51",
            "SST": "53",
            "LANG": "74"
        },
        {
            "AdmNo": "11684",
            "Student_name": "SMRUTIREKHA PATRO",
            "RollNo": "35",
            "Sec": "D",
            "ENGLISH": "69",
            "MATHEMATICS": "58",
            "SCIENCE": "49",
            "SST": "59",
            "LANG": "69"
        },
        {
            "AdmNo": "11686",
            "Student_name": "SADHIKA DAS",
            "RollNo": "36",
            "Sec": "E",
            "ENGLISH": "77",
            "MATHEMATICS": "78",
            "SCIENCE": "69",
            "SST": "65",
            "LANG": "76"
        },
        {
            "AdmNo": "11691",
            "Student_name": "PRATHNA PARIDA",
            "RollNo": "29",
            "Sec": "C",
            "ENGLISH": "63",
            "MATHEMATICS": "25",
            "SCIENCE": "30",
            "SST": "48",
            "LANG": "64"
        },
        {
            "AdmNo": "11693",
            "Student_name": "BHARAT TRIPATHY",
            "RollNo": "18",
            "Sec": "C",
            "ENGLISH": "75",
            "MATHEMATICS": "60",
            "SCIENCE": "56",
            "SST": "64",
            "LANG": "68"
        },
        {
            "AdmNo": "11722",
            "Student_name": "ANJALI MISHRA",
            "RollNo": "7",
            "Sec": "F",
            "ENGLISH": "77",
            "MATHEMATICS": "75",
            "SCIENCE": "72",
            "SST": "73",
            "LANG": "77"
        },
        {
            "AdmNo": "11740",
            "Student_name": "PEEYALI PRIYADARSHINI",
            "RollNo": "17",
            "Sec": "A",
            "ENGLISH": "73",
            "MATHEMATICS": "64",
            "SCIENCE": "58",
            "SST": "63",
            "LANG": "70"
        },
        {
            "AdmNo": "11744",
            "Student_name": "ARPITA BEHERA",
            "RollNo": "7",
            "Sec": "A",
            "ENGLISH": "77",
            "MATHEMATICS": "67",
            "SCIENCE": "60",
            "SST": "60",
            "LANG": "78"
        },
        {
            "AdmNo": "11873",
            "Student_name": "SHREYANSI DAS",
            "RollNo": "31",
            "Sec": "D",
            "ENGLISH": "59",
            "MATHEMATICS": "40",
            "SCIENCE": "46",
            "SST": "60",
            "LANG": "67"
        },
        {
            "AdmNo": "11875",
            "Student_name": "AKSHITA SARAH",
            "RollNo": "5",
            "Sec": "E",
            "ENGLISH": "73",
            "MATHEMATICS": "70",
            "SCIENCE": "64",
            "SST": "71",
            "LANG": "73"
        },
        {
            "AdmNo": "12397",
            "Student_name": "RUHIKA DAS",
            "RollNo": "36",
            "Sec": "C",
            "ENGLISH": "79",
            "MATHEMATICS": "80",
            "SCIENCE": "80",
            "SST": "79",
            "LANG": "80"
        },
        {
            "AdmNo": "12398",
            "Student_name": "DEEPESH KUMAR PANDA",
            "RollNo": "18",
            "Sec": "F",
            "ENGLISH": "77",
            "MATHEMATICS": "79",
            "SCIENCE": "74",
            "SST": "75",
            "LANG": "77"
        },
        {
            "AdmNo": "12403",
            "Student_name": "RISHIKA SAHOO",
            "RollNo": "33",
            "Sec": "E",
            "ENGLISH": "77",
            "MATHEMATICS": "66",
            "SCIENCE": "63",
            "SST": "75",
            "LANG": "73"
        },
        {
            "AdmNo": "12409",
            "Student_name": "PRIYANSHU JENA",
            "RollNo": "36",
            "Sec": "F",
            "ENGLISH": "76",
            "MATHEMATICS": "80",
            "SCIENCE": "76",
            "SST": "76",
            "LANG": "74"
        },
        {
            "AdmNo": "12420",
            "Student_name": "ANWESHA RATH",
            "RollNo": "10",
            "Sec": "F",
            "ENGLISH": "79",
            "MATHEMATICS": "75",
            "SCIENCE": "75",
            "SST": "77",
            "LANG": "80"
        },
        {
            "AdmNo": "12595",
            "Student_name": "NABYASHA BEHERA",
            "RollNo": "27",
            "Sec": "E",
            "ENGLISH": "62",
            "MATHEMATICS": "38",
            "SCIENCE": "41",
            "SST": "49",
            "LANG": "59"
        },
        {
            "AdmNo": "12653",
            "Student_name": "HRISHITA MOHANTY",
            "RollNo": "47",
            "Sec": "C",
            "ENGLISH": "74",
            "MATHEMATICS": "62",
            "SCIENCE": "67",
            "SST": "73",
            "LANG": "78"
        },
        {
            "AdmNo": "12666",
            "Student_name": "KRISHNA PRASAD SAHOO",
            "RollNo": "9",
            "Sec": "B",
            "ENGLISH": "66",
            "MATHEMATICS": "58",
            "SCIENCE": "45",
            "SST": "56",
            "LANG": "62"
        },
        {
            "AdmNo": "12694",
            "Student_name": "RIDDHI RUCHIRA MISHRA",
            "RollNo": "34",
            "Sec": "C",
            "ENGLISH": "79",
            "MATHEMATICS": "80",
            "SCIENCE": "77",
            "SST": "75",
            "LANG": "80"
        },
        {
            "AdmNo": "12889",
            "Student_name": "AAYUSH MEHER",
            "RollNo": "17",
            "Sec": "C",
            "ENGLISH": "68",
            "MATHEMATICS": "53",
            "SCIENCE": "45",
            "SST": "36",
            "LANG": "54"
        },
        {
            "AdmNo": "13378",
            "Student_name": "CHELSEA NAYAK",
            "RollNo": "15",
            "Sec": "E",
            "ENGLISH": "66",
            "MATHEMATICS": "46",
            "SCIENCE": "50",
            "SST": "65",
            "LANG": "72"
        },
        {
            "AdmNo": "13386",
            "Student_name": "AVISYA SAMAL",
            "RollNo": "11",
            "Sec": "E",
            "ENGLISH": "75",
            "MATHEMATICS": "80",
            "SCIENCE": "74",
            "SST": "74",
            "LANG": "73"
        },
        {
            "AdmNo": "13387",
            "Student_name": "PRATIK PRIYANSHU DAS",
            "RollNo": "30",
            "Sec": "C",
            "ENGLISH": "75",
            "MATHEMATICS": "70",
            "SCIENCE": "70",
            "SST": "74",
            "LANG": "79"
        },
        {
            "AdmNo": "13388",
            "Student_name": "ADITYA PRASAD TRIPATHY",
            "RollNo": "3",
            "Sec": "F",
            "ENGLISH": "67",
            "MATHEMATICS": "61",
            "SCIENCE": "55",
            "SST": "65",
            "LANG": "69"
        },
        {
            "AdmNo": "13420",
            "Student_name": "ABHISHEK DAS",
            "RollNo": "2",
            "Sec": "C",
            "ENGLISH": "70",
            "MATHEMATICS": "62",
            "SCIENCE": "66",
            "SST": "69",
            "LANG": "69"
        },
        {
            "AdmNo": "13717",
            "Student_name": "AYUSH BARAL",
            "RollNo": "12",
            "Sec": "E",
            "ENGLISH": "61",
            "MATHEMATICS": "56",
            "SCIENCE": "43",
            "SST": "47",
            "LANG": "65"
        },
        {
            "AdmNo": "13721",
            "Student_name": "SPANDAN SATPATHY",
            "RollNo": "46",
            "Sec": "F",
            "ENGLISH": "72",
            "MATHEMATICS": "80",
            "SCIENCE": "76",
            "SST": "73",
            "LANG": "73"
        },
        {
            "AdmNo": "13724",
            "Student_name": "PRERNA BHUNIYA",
            "RollNo": "29",
            "Sec": "E",
            "ENGLISH": "72",
            "MATHEMATICS": "76",
            "SCIENCE": "71",
            "SST": "65",
            "LANG": "74"
        },
        {
            "AdmNo": "13749",
            "Student_name": "SUHANI SAHASMAL",
            "RollNo": "45",
            "Sec": "E",
            "ENGLISH": "76",
            "MATHEMATICS": "78",
            "SCIENCE": "60",
            "SST": "71",
            "LANG": "73"
        },
        {
            "AdmNo": "13866",
            "Student_name": "PRATEEK MISHRA",
            "RollNo": "28",
            "Sec": "C",
            "ENGLISH": "68",
            "MATHEMATICS": "48",
            "SCIENCE": "49",
            "SST": "66",
            "LANG": "64"
        },
        {
            "AdmNo": "13870",
            "Student_name": "RAAYAN MOHANTY",
            "RollNo": "23",
            "Sec": "A",
            "ENGLISH": "67",
            "MATHEMATICS": "27",
            "SCIENCE": "46",
            "SST": "AB",
            "LANG": "65"
        },
        {
            "AdmNo": "13871",
            "Student_name": "VISHES NATH",
            "RollNo": "48",
            "Sec": "E",
            "ENGLISH": "47",
            "MATHEMATICS": "26",
            "SCIENCE": "34",
            "SST": "29",
            "LANG": "36"
        },
        {
            "AdmNo": "13874",
            "Student_name": "AKSHIT DAS",
            "RollNo": "4",
            "Sec": "E",
            "ENGLISH": "73",
            "MATHEMATICS": "76",
            "SCIENCE": "74",
            "SST": "76",
            "LANG": "76"
        },
        {
            "AdmNo": "13885",
            "Student_name": "HITESH KUMAR PANDA",
            "RollNo": "23",
            "Sec": "C",
            "ENGLISH": "72",
            "MATHEMATICS": "37",
            "SCIENCE": "51",
            "SST": "65",
            "LANG": "67"
        },
        {
            "AdmNo": "13899",
            "Student_name": "SIDDHANT SHIVAM",
            "RollNo": "43",
            "Sec": "F",
            "ENGLISH": "74",
            "MATHEMATICS": "79",
            "SCIENCE": "70",
            "SST": "73",
            "LANG": "74"
        },
        {
            "AdmNo": "13978",
            "Student_name": "JYOTIRADITYA ROUT",
            "RollNo": "18",
            "Sec": "D",
            "ENGLISH": "62",
            "MATHEMATICS": "52",
            "SCIENCE": "51",
            "SST": "61",
            "LANG": "73"
        },
        {
            "AdmNo": "14364",
            "Student_name": "RUPIN SHEKHAR",
            "RollNo": "35",
            "Sec": "E",
            "ENGLISH": "59",
            "MATHEMATICS": "53",
            "SCIENCE": "58",
            "SST": "61",
            "LANG": "67"
        },
        {
            "AdmNo": "14383",
            "Student_name": "KOLLA HARSHIT",
            "RollNo": "22",
            "Sec": "E",
            "ENGLISH": "76",
            "MATHEMATICS": "78",
            "SCIENCE": "74",
            "SST": "80",
            "LANG": "77"
        },
        {
            "AdmNo": "14418",
            "Student_name": "ARNAB JENA",
            "RollNo": "6",
            "Sec": "A",
            "ENGLISH": "74",
            "MATHEMATICS": "76",
            "SCIENCE": "72",
            "SST": "70",
            "LANG": "70"
        },
        {
            "AdmNo": "14421",
            "Student_name": "UDAYAN SAHOO",
            "RollNo": "45",
            "Sec": "D",
            "ENGLISH": "67",
            "MATHEMATICS": "51",
            "SCIENCE": "53",
            "SST": "62",
            "LANG": "60"
        },
        {
            "AdmNo": "14492",
            "Student_name": "PRARTHANA SAHANI",
            "RollNo": "23",
            "Sec": "D",
            "ENGLISH": "67",
            "MATHEMATICS": "36",
            "SCIENCE": "35",
            "SST": "47",
            "LANG": "72"
        },
        {
            "AdmNo": "14644",
            "Student_name": "JOHN JAMES",
            "RollNo": "20",
            "Sec": "E",
            "ENGLISH": "AB",
            "MATHEMATICS": "AB",
            "SCIENCE": "AB",
            "SST": "AB",
            "LANG": "AB"
        },
        {
            "AdmNo": "14835",
            "Student_name": "DIBYAJYOTI DAS MOHAPATRA",
            "RollNo": "17",
            "Sec": "E",
            "ENGLISH": "62",
            "MATHEMATICS": "28",
            "SCIENCE": "31",
            "SST": "54",
            "LANG": "65"
        },
        {
            "AdmNo": "14841",
            "Student_name": "AMLAN SAHU",
            "RollNo": "5",
            "Sec": "A",
            "ENGLISH": "76",
            "MATHEMATICS": "70",
            "SCIENCE": "76",
            "SST": "79",
            "LANG": "74"
        },
        {
            "AdmNo": "14978",
            "Student_name": "SAMUDRA PATTANAIK",
            "RollNo": "39",
            "Sec": "F",
            "ENGLISH": "77",
            "MATHEMATICS": "79",
            "SCIENCE": "80",
            "SST": "78",
            "LANG": "80"
        },
        {
            "AdmNo": "14990",
            "Student_name": "TAMANNA PRIYADARSHINI NAYAK",
            "RollNo": "42",
            "Sec": "B",
            "ENGLISH": "79",
            "MATHEMATICS": "78",
            "SCIENCE": "72",
            "SST": "74",
            "LANG": "80"
        },
        {
            "AdmNo": "15043",
            "Student_name": "PRIYANKA PRIYADARSHINI BARIK",
            "RollNo": "20",
            "Sec": "B",
            "ENGLISH": "76",
            "MATHEMATICS": "74",
            "SCIENCE": "66",
            "SST": "72",
            "LANG": "79"
        },
        {
            "AdmNo": "15051",
            "Student_name": "SRISHTI TRIPATHY",
            "RollNo": "41",
            "Sec": "E",
            "ENGLISH": "77",
            "MATHEMATICS": "77",
            "SCIENCE": "76",
            "SST": "70",
            "LANG": "78"
        },
        {
            "AdmNo": "15054",
            "Student_name": "SHRUTI AMRITA PANDA",
            "RollNo": "34",
            "Sec": "B",
            "ENGLISH": "69",
            "MATHEMATICS": "0",
            "SCIENCE": "56",
            "SST": "52",
            "LANG": "60"
        },
        {
            "AdmNo": "15073",
            "Student_name": "BISHAKHA PARHI",
            "RollNo": "19",
            "Sec": "C",
            "ENGLISH": "75",
            "MATHEMATICS": "66",
            "SCIENCE": "70",
            "SST": "77",
            "LANG": "80"
        },
        {
            "AdmNo": "15079",
            "Student_name": "SANLLY MISHRA",
            "RollNo": "38",
            "Sec": "C",
            "ENGLISH": "60",
            "MATHEMATICS": "32",
            "SCIENCE": "37",
            "SST": "42",
            "LANG": "68"
        },
        {
            "AdmNo": "15082",
            "Student_name": "DEEPSHREE SAHOO",
            "RollNo": "19",
            "Sec": "F",
            "ENGLISH": "75",
            "MATHEMATICS": "79",
            "SCIENCE": "74",
            "SST": "77",
            "LANG": "75"
        },
        {
            "AdmNo": "15083",
            "Student_name": "RISHIKA CHAND",
            "RollNo": "32",
            "Sec": "E",
            "ENGLISH": "71",
            "MATHEMATICS": "58",
            "SCIENCE": "53",
            "SST": "64",
            "LANG": "75"
        },
        {
            "AdmNo": "15087",
            "Student_name": "ANKIT KUMAR",
            "RollNo": "10",
            "Sec": "C",
            "ENGLISH": "72",
            "MATHEMATICS": "76",
            "SCIENCE": "75",
            "SST": "75",
            "LANG": "77"
        },
        {
            "AdmNo": "15481",
            "Student_name": "MRUDU MANGAL SAHOO",
            "RollNo": "28",
            "Sec": "F",
            "ENGLISH": "70",
            "MATHEMATICS": "70",
            "SCIENCE": "49",
            "SST": "60",
            "LANG": "76"
        },
        {
            "AdmNo": "15482",
            "Student_name": "KASISH PRIYADARSINI PRADHAN",
            "RollNo": "21",
            "Sec": "E",
            "ENGLISH": "70",
            "MATHEMATICS": "61",
            "SCIENCE": "62",
            "SST": "66",
            "LANG": "77"
        },
        {
            "AdmNo": "15484",
            "Student_name": "ARPIT DASH",
            "RollNo": "7",
            "Sec": "E",
            "ENGLISH": "67",
            "MATHEMATICS": "65",
            "SCIENCE": "46",
            "SST": "59",
            "LANG": "61"
        },
        {
            "AdmNo": "15487",
            "Student_name": "SUBHETSHA BEHERA",
            "RollNo": "45",
            "Sec": "C",
            "ENGLISH": "76",
            "MATHEMATICS": "44",
            "SCIENCE": "58",
            "SST": "72",
            "LANG": "74"
        },
        {
            "AdmNo": "15505",
            "Student_name": "JAY MISHRA",
            "RollNo": "19",
            "Sec": "E",
            "ENGLISH": "73",
            "MATHEMATICS": "76",
            "SCIENCE": "71",
            "SST": "67",
            "LANG": "75"
        },
        {
            "AdmNo": "15528",
            "Student_name": "SUDESHNA SAHOO",
            "RollNo": "44",
            "Sec": "E",
            "ENGLISH": "65",
            "MATHEMATICS": "46",
            "SCIENCE": "53",
            "SST": "50",
            "LANG": "73"
        },
        {
            "AdmNo": "15540",
            "Student_name": "PRATEEK SAHOO",
            "RollNo": "44",
            "Sec": "C",
            "ENGLISH": "75",
            "MATHEMATICS": "65",
            "SCIENCE": "47",
            "SST": "63",
            "LANG": "72"
        },
        {
            "AdmNo": "15574",
            "Student_name": "SOUMYA SRICHANDAN",
            "RollNo": "37",
            "Sec": "B",
            "ENGLISH": "75",
            "MATHEMATICS": "78",
            "SCIENCE": "69",
            "SST": "74",
            "LANG": "80"
        },
        {
            "AdmNo": "15632",
            "Student_name": "SAMPAD PADHEE",
            "RollNo": "44",
            "Sec": "D",
            "ENGLISH": "56",
            "MATHEMATICS": "24",
            "SCIENCE": "27",
            "SST": "56",
            "LANG": "59"
        }
    ]

    export default arr 